[package]
name = "ingraind"
version = "0.1.0"
authors = ["vagrant"]
build = "build.rs"

[build-dependencies]
failure = "0.1"
bindgen = "0.37"
regex = "1.0"
lazy_static = "1.0"
redbpf = { path = "./redbpf" }

[dependencies]
actix = "^0.7"
futures = "^0.1"
tokio = "0.1"

failure = "0.1"

libc = "0.2"
lazy-socket = "0.3"
redbpf = { path = "./redbpf" }

uuid = { version = "0.6", features = ["v4"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
toml = "^0.4"

rustls = "0.13"
epoll = "4.0"
metrohash = "1"
regex = "1.0"

[dependencies.cadence]
version =  "0.14"
optional = true

[dependencies.rusoto_core]
git = "https://github.com/redsift/rusoto"
features = ["rustls"]
default-features = false
optional = true

[dependencies.rusoto_s3]
git = "https://github.com/redsift/rusoto"
optional = true

[features]
default = ["statsd-backend", "s3-backend"]
s3-backend = ["rusoto_core", "rusoto_s3"]
statsd-backend = ["cadence"]