[package]
name = "ingraind"
version = "0.1.0"
authors = ["vagrant"]
build = "build.rs"

[build-dependencies]
failure = "0.1"
bindgen = "0.37"
regex = "1.0"
lazy_static = "1.0"
redbpf = { path = "./redbpf" }

[dependencies]
actix = "^0.7"
futures = "^0.1"
tokio = "0.1"

failure = "0.1"

libc = "0.2"
lazy-socket = "0.3"
redbpf = { path = "./redbpf" }

uuid = { version = "0.6", features = ["v4"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
toml = "^0.4"

cadence = "0.14"
rusoto_core = "0.32"
rusoto_s3 = "0.32"

rustls = "0.13"
epoll = "4.0"
ring = "0.13"