[package]
name = "tcpsniff-rs"
version = "0.1.0"
authors = ["vagrant"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
libc = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.6", features = ["v4"] }
