version: 2
jobs:
  docker:
    environment:
      CONTAINER_NAME: "quay.io/redsift/ingraind"

    working_directory: /tmp/ws/build
    docker:
      - image: docker:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/ws

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to a regsitry
          command: |
            echo ${QUAY_PASS} | docker login --username ${QUAY_USER} --password-stdin quay.io

      - run:
          name: Build Docker image
          command: |
            export TAG=${CIRCLE_TAG:-unknown}
            export SHA=${CIRCLE_SHA1:0:7}
            docker build -f docker/Dockerfile.quay -t $CONTAINER_NAME:latest -t $CONTAINER_NAME:$SHA .

            echo "Total sizes"
            docker images $CONTAINER_NAME
            docker push $CONTAINER_NAME 

  static:
    working_directory: /build
    docker:
      - image: quay.io/redsift/ingraind-build:latest
    steps:
      - checkout
      - attach_workspace:
          at: /build

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build static binary
          command: |
            cargo build --target=x86_64-unknown-linux-musl --release || exit 1

      - store_artifacts:
          path: /build/target/x86_64-unknown-linux-musl/release/ingraind 
          destination: ingraind

workflows:
  version: 2
  build_pack:
    jobs:
      - docker
      - static
