version: 2.1
commands:
  install_rust:
    steps:
      - run:
          name: Install rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf -o rustup.sh https://sh.rustup.rs
            chmod 755 rustup.sh
            ./rustup.sh -y
            . /root/.cargo/env
            rustup target add x86_64-unknown-linux-musl
            rustup component add rustfmt

jobs:
  terraform:
    parameters:
      ami:
        type: string
        default: "latest"
    working_directory: /build
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run:
          name: Deploy
          command: |
            cd terraform
            ./run-test.sh << parameters.ami >>

  ubuntu:
    parameters:
      tag:
        type: string
        default: "latest"
      kernel_version:
        type: string
        default: "$(uname -r)"
    working_directory: /build
    docker:
      - image: ubuntu:<< parameters.tag >>
    steps:
      - checkout
      - attach_workspace:
          at: /build

      - run:
          name: Install deps
          command: |
            apt-get update
            apt-get install -y curl clang llvm musl-tools capnproto libelf-dev linux-headers-<< parameters.kernel_version >> ca-certificates{,-java}

      - install_rust

      - run:
          name: Build static binary
          command: |
            . /root/.cargo/env
            cargo test --target=x86_64-unknown-linux-musl --release || exit 1
            cargo build --target=x86_64-unknown-linux-musl --release || exit 1

            mkdir -p /tmp/workspace/bin
            cp target/x86_64-unknown-linux-musl/release/ingraind \
               /tmp/workspace/bin/ingraind-ubuntu-$(echo "<< parameters.tag >>" | sed 's/\.//')

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bin


  fedora:
    working_directory: /build
    docker:
      - image: fedora:29
    steps:
      - checkout
      - attach_workspace:
          at: /build

      - run:
          name: Install deps
          command: |
            yum install -y clang llvm capnproto kernel-4.18.16-300.fc29.x86_64 kernel-devel-4.18.16-300.fc29.x86_64 elfutils-libelf-devel ca-certificates

      - install_rust

      - run:
          name: Build
          command: |
            . /root/.cargo/env
            export KERNEL_VERSION=4.18.16-300.fc29.x86_64
            cargo test --release || exit 1
            cargo build --release || exit 1

  build_docker_image:
    environment:
      CONTAINER_NAME: "quay.io/redsift/ingraind"

    working_directory: /build
    docker:
      - image: docker:latest
    steps:
      - checkout
      - attach_workspace:
          at: /build

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to a regsitry
          command: |
            echo ${QUAY_PASS} | docker login --username ${QUAY_USER} --password-stdin quay.io

      - run:
          name: Build Docker image
          command: |
            export TAG=${CIRCLE_TAG:-unknown}
            export SHA=${CIRCLE_SHA1:0:7}

            cd /build
            cp /build/target/x86_64-unknown-linux-musl/release/ingraind .
            docker build --build-arg BINARY_PATH=./ingraind \
                   -f docker/Dockerfile.static \
                   -t $CONTAINER_NAME:latest \
                   -t $CONTAINER_NAME:$SHA \
                   /build

            echo "Total sizes"
            docker images $CONTAINER_NAME
            docker push $CONTAINER_NAME

  build_docker_binary:
    working_directory: /build
    docker:
      - image: quay.io/redsift/ingraind-build:latest
    steps:
      - checkout
      - attach_workspace:
          at: /build

      - run:
          name: Build static binary
          command: |
            cargo test --target=x86_64-unknown-linux-musl --release || exit 1
            cargo build --target=x86_64-unknown-linux-musl --release || exit 1

      - persist_to_workspace:
          root: "./"
          paths:
            - "target"

      - store_artifacts:
          path: /build/target/x86_64-unknown-linux-musl/release/ingraind
          destination: ingraind

workflows:
  version: 2.1
  build:
    jobs:
      - terraform:
         name: 'terraform - ubuntu 18.04'
         ami: 'ubuntu-1804' 
         requires:
           - ubuntu 18.04

      - ubuntu:
          name: "ubuntu 18.04"
          tag: "18.04"

      - ubuntu:
          name: "ubuntu 16.04"
          tag: "16.04"
          filters:
            branches:
              only:
                - master

      - fedora:
          name: "fedora 29"
          filters:
            branches:
              only:
                - master

      - build_docker_binary:
          filters:
            branches:
              only:
                - master

      - build_docker_image:
          requires:
            - build_docker_binary
