version: 2
jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Install clang & linux-headers
          command: apt-get update && apt-get -y install clang linux-headers-amd64
      - run:
          name: Version information
          command: rustc --version; rustup --version; cargo --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile --verbose
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --release --verbose
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --verbose
