version: 2
jobs:
  pack:
    environment:
      CONTAINER_NAME: "quay.io/redsift/ingraind"

    working_directory: /build
    docker:
      - image: docker:latest
    steps:
      - checkout
      - attach_workspace:
          at: /build

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to a regsitry
          command: |
            echo ${QUAY_PASS} | docker login --username ${QUAY_USER} --password-stdin quay.io

      - run:
          name: Build Docker image
          command: |
            export TAG=${CIRCLE_TAG:-unknown}
            export SHA=${CIRCLE_SHA1:0:7}

            cd /build
            cp /build/target/x86_64-unknown-linux-musl/release/ingraind .
            docker build --build-arg BINARY_PATH=./ingraind \
                   -f docker/Dockerfile.static \
                   -t $CONTAINER_NAME:latest \
                   -t $CONTAINER_NAME:$SHA \
                   /build

            echo "Total sizes"
            docker images $CONTAINER_NAME
            docker push $CONTAINER_NAME 

  build:
    working_directory: /build
    docker:
      - image: quay.io/redsift/ingraind-build:latest
    steps:
      - checkout
      - attach_workspace:
          at: /build

      - restore_cache:
          keys:
            - ingraind-cargo

      - run:
          name: Build static binary
          command: |
            cargo test --target=x86_64-unknown-linux-musl --release || exit 1
            cargo build --target=x86_64-unknown-linux-musl --release || exit 1

      - save_cache:
          key: ingraind-cargo
          paths:
            - "/usr/local/cargo"
            - "/build/target/"

      - persist_to_workspace:
          root: "./"
          paths:
            - "target"

      - store_artifacts:
          path: /build/target/x86_64-unknown-linux-musl/release/ingraind 
          destination: ingraind

workflows:
  version: 2
  build_pack:
    jobs:
      - build
      - pack:
          requires:
            - build
